### ISSUE TITLE
More windows errors

### ISSUE THREAD

**Issue by johnkubik** [JuicyPasta/Claymore-No-Fee-Proxy#3]
The following error happens approx every 3 hours. I am keeping wireshark open so I can send PCAP data with it.

Traceback (most recent call last):
  File "c:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File ".\proxy\stratum_proxy.py", line 121, in proxy_handler
    remote_socket.send(local_buffer)
error: [Errno 10053] An established connection was aborted by the software in your host machine

**Comment by drdada** [comment]
Yes i had the same issue, this is because the remote pool closed the connection. I already have fixed it in my local repo. I will push it ASAP.

**Comment by drdada** [comment]
Fixed: 3ced6e9
